{
  "openapi": "3.0.1",
  "info": {
    "version": "2024-09-19T22:56:24Z",
    "title": "task11_api",
    "description": "Task 11 OpenAPI documentation AWS service",
    "contact": {
      "name": "Alex ILIN",
      "email": "oleksandr_ilin@epam.com"
    },
    "license": {
      "name": ""
    }
  },
  "servers": [
    {
      "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
      "variables": {
        "basePath": {
          "default": "api"
        }
      }
    }
  ],
  "paths": {
    "/signup": {
      "post": {
        "summary": "Creates a new user",
        "description": "SignUp as a new user",
        "operationId": "signup-post",
        "requestBody": {
          "$ref": "#/components/requestBodies/SignUpRequest"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/SimpleResponse"
          },
          "400": {
            "$ref": "#/components/responses/SimpleResponse"
          }
        },
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "aws_proxy",
          "httpMethod": "POST",
          "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:905418349556:function:api_handler/invocations",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match"
        }
      },
      "options": {
        "operationId": "signup-options",
        "responses": {
          "200": {
            "description": "200 response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            },
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Methods": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Headers": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "mock",
          "responses": {
            "default": {
              "statusCode": "200",
              "responseParameters": {
                "method.response.header.Access-Control-Allow-Methods": "'*'",
                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              }
            }
          },
          "requestTemplates": {
            "application/json": "{\"statusCode\": 200}"
          },
          "passthroughBehavior": "when_no_match"
        }
      }
    },
    "/signin": {
      "post": {
        "summary": "SignIn",
        "description": "Execute the Sign In operation to authenticate and authorize the user and get the access token",
        "operationId": "signin-post",
        "requestBody": {
          "$ref": "#/components/requestBodies/SignInRequest"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/SignInResponse"
          },
          "400": {
            "$ref": "#/components/responses/SimpleResponse"
          }
        },
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "aws_proxy",
          "httpMethod": "POST",
          "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:905418349556:function:api_handler/invocations",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match"
        }
      },
      "options": {
        "operationId": "signin-options",
        "responses": {
          "200": {
            "description": "200 response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            },
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Methods": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Headers": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "mock",
          "responses": {
            "default": {
              "statusCode": "200",
              "responseParameters": {
                "method.response.header.Access-Control-Allow-Methods": "'*'",
                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              }
            }
          },
          "requestTemplates": {
            "application/json": "{\"statusCode\": 200}"
          },
          "passthroughBehavior": "when_no_match"
        }
      }
    },
    "/tables": {
      "get": {
        "summary": "Lists all tables",
        "description": "Loads all tables from **DynamoDB** and lists it as *json* response",
        "operationId": "tables-get",
        "responses": {
          "200": {
            "$ref": "#/components/responses/TableListResponse"
          },
          "400": {
            "$ref": "#/components/responses/SimpleResponse"
          }
        },
        "security": [
          {
            "authorizer": []
          }
        ],
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "aws_proxy",
          "httpMethod": "POST",
          "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:905418349556:function:api_handler/invocations",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match"
        }
      },
      "post": {
        "summary": "Adds a new table",
        "description": "Adds a new table and store it in the **DynamoDB**",
        "operationId": "tables-post",
        "requestBody": {
          "$ref": "#/components/requestBodies/NewTableRequest"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/NewTableAddedResponse"
          },
          "400": {
            "$ref": "#/components/responses/SimpleResponse"
          }
        },
        "security": [
          {
            "authorizer": []
          }
        ],
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "aws_proxy",
          "httpMethod": "POST",
          "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:905418349556:function:api_handler/invocations",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match"
        }
      },
      "options": {
        "operationId": "tables-options",
        "responses": {
          "200": {
            "description": "200 response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            },
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Methods": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Headers": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "mock",
          "responses": {
            "default": {
              "statusCode": "200",
              "responseParameters": {
                "method.response.header.Access-Control-Allow-Methods": "'*'",
                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              }
            }
          },
          "requestTemplates": {
            "application/json": "{\"statusCode\": 200}"
          },
          "passthroughBehavior": "when_no_match"
        }
      }
    },
    "/tables/{tableId}": {
      "get": {
        "summary": "Shows the table details",
        "description": "Finds the table information by the **table Id**",
        "operationId": "tables-byid-get",
        "parameters": [
          {
            "name": "tableId",
            "in": "path",
            "description": "The table number which information you are looking for",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/TableResponse"
          },
          "400": {
            "$ref": "#/components/responses/SimpleResponse"
          }
        },
        "security": [
          {
            "authorizer": []
          }
        ],
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "aws_proxy",
          "httpMethod": "POST",
          "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:905418349556:function:api_handler/invocations",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match"
        }
      },
      "options": {
        "operationId": "tables-byid-options",
        "parameters": [
          {
            "name": "tableId",
            "in": "path",
            "description": "The table number which information you are looking for",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            },
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Methods": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Headers": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "mock",
          "responses": {
            "default": {
              "statusCode": "200",
              "responseParameters": {
                "method.response.header.Access-Control-Allow-Methods": "'*'",
                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              }
            }
          },
          "requestTemplates": {
            "application/json": "{\"statusCode\": 200}"
          },
          "passthroughBehavior": "when_no_match"
        }
      }
    },
    "/reservations": {
      "get": {
        "summary": "Lists all reservations",
        "description": "Loads all reservations from **DynamoDB** and lists it as *json* response",
        "operationId": "reservations-get",
        "responses": {
          "200": {
            "$ref": "#/components/responses/ReservationListResponse"
          },
          "400": {
            "$ref": "#/components/responses/SimpleResponse"
          }
        },
        "security": [
          {
            "authorizer": []
          }
        ],
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "aws_proxy",
          "httpMethod": "POST",
          "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:905418349556:function:api_handler/invocations",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match"
        }
      },
      "post": {
        "summary": "Add a new reservation",
        "description": "Adds a new reservation if:\n- requested *table* exists and \n- it does not overlap other existed reservations for this *table*",
        "operationId": "reservations-post",
        "requestBody": {
          "$ref": "#/components/requestBodies/AddNewReservationRequest"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/ReservationResultResponse"
          },
          "400": {
            "$ref": "#/components/responses/SimpleResponse"
          }
        },
        "security": [
          {
            "authorizer": []
          }
        ],
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "aws_proxy",
          "httpMethod": "POST",
          "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:905418349556:function:api_handler/invocations",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match"
        }
      },
      "options": {
        "operationId": "reservations-options",
        "responses": {
          "200": {
            "description": "200 response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            },
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Methods": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Headers": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "servers": [
          {
            "url": "https://yuk8h205ik.execute-api.eu-central-1.amazonaws.com/{basePath}",
            "variables": {
              "basePath": {
                "default": "api"
              }
            }
          }
        ],
        "x-amazon-apigateway-integration": {
          "responses": {
            "default": {
              "statusCode": "200",
              "responseParameters": {
                "method.response.header.Access-Control-Allow-Methods": "'*'",
                "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              }
            }
          },
          "requestTemplates": {
            "application/json": "{\"statusCode\": 200}"
          },
          "passthroughBehavior": "when_no_match",
          "type": "mock"
        }
      }
    }
  },
  "tags": [
    {
      "name": "task11"
    }
  ],
  "components": {
    "requestBodies": {
      "SignUpRequest": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "title": "SignUpRequest",
              "description": "A new user data",
              "properties": {
                "firstName": {
                  "type": "string",
                  "description": "The user First Name",
                  "example": "Mary"
                },
                "lastName": {
                  "type": "string",
                  "description": "The user Last Name",
                  "example": "Smith"
                },
                "email": {
                  "type": "string",
                  "description": "The user email which would be used as unique user identifier in the system",
                  "example": "mary-smith@example.com"
                },
                "password": {
                  "type": "string",
                  "description": "The user password. Should be alphanumeric + any of \"$%^*\", 12+ chars",
                  "pattern": "^(?=.*[A-Za-z0-9])(?=.*[$%^*]).{12,}$",
                  "example": "testPass34$354545"
                }
              },
              "required": [
                "firstName",
                "lastName",
                "email"
              ]
            },
            "examples": {
              "Example 1": {
                "value": {
                  "firstName": "Mary",
                  "lastName": "Smith",
                  "email": "mary-smith@example.com",
                  "password": "testPass34$354545"
                }
              }
            }
          }
        }
      },
      "SignInRequest": {
        "description": "Used to sign in and receive the acess token",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "minLength": 6,
                  "example": "test@email.com"
                },
                "password": {
                  "type": "string",
                  "format": "password",
                  "pattern": "^(?=.*[A-Za-z0-9])(?=.*[$%^*]).{12,}$",
                  "minLength": 12,
                  "example": "testPass34$354545"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "email": "test@email.com",
                  "password": "testPass34$354545"
                }
              }
            }
          }
        }
      },
      "NewTableRequest": {
        "description": "New Table Request",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Table"
            },
            "examples": {
              "Example 1": {
                "value": {
                  "id": 25,
                  "number": 12,
                  "places": 5,
                  "isVip": true,
                  "minOrder": 0
                }
              }
            }
          }
        }
      },
      "AddNewReservationRequest": {
        "description": "New Reservation",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Reservation"
            },
            "examples": {
              "Example 1": {
                "value": {
                  "tableNumber": 12,
                  "clientName": "Jim Smith",
                  "phoneNumber": "949 213-3433",
                  "date": "2024-09-20",
                  "slotTimeStart": "3:00",
                  "slotTimeEnd": "15:00"
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "authorizer": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header",
        "x-amazon-apigateway-authtype": "cognito_user_pools",
        "x-amazon-apigateway-authorizer": {
          "type": "cognito_user_pools",
          "x-syndicate-cognito-userpool-names": ["${booking_userpool}"]
        }
      }
    },
    "responses": {
      "SignInResponse": {
        "description": "The access token",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "accessToken": {
                  "type": "string"
                }
              },
              "x-examples": {
                "Example 1": {
                  "accessToken": "jwt-token"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "accessToken": "// string"
                }
              }
            }
          }
        }
      },
      "SimpleResponse": {
        "description": "{\n    \"message\": \"Some result details\"\n}",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "x-examples": {
                "Example 1": {
                  "message": "Some message"
                }
              }
            }
          }
        }
      },
      "TableListResponse": {
        "description": "List of available tables",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "tables": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Table"
                  }
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "tables": [
                    {
                      "id": 25,
                      "number": 12,
                      "places": 5,
                      "isVip": true,
                      "minOrder": 0
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "TableResponse": {
        "description": "Table details",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Table"
            },
            "examples": {
              "Example 1": {
                "value": {
                  "id": 25,
                  "number": 12,
                  "places": 5,
                  "isVip": true,
                  "minOrder": 0
                }
              }
            }
          }
        }
      },
      "NewTableAddedResponse": {
        "description": "New Table info",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "format": "int64"
                }
              },
              "example": {
                "id": 24
              }
            },
            "examples": {
              "default": {
                "value": {
                  "id": 24
                }
              }
            }
          }
        }
      },
      "ReservationResultResponse": {
        "description": "Just added reservation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "reservationId": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "reservationId": "string"
                }
              }
            }
          }
        }
      },
      "ReservationListResponse": {
        "description": "List of reservations",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "reservations": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Reservation"
                  }
                }
              }
            }
          }
        }
      }
    },
    "schemas": {
      "Empty": {
        "type": "object",
        "title": "Empty Schema"
      },
      "Table": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "example": 25
          },
          "number": {
            "type": "integer",
            "format": "int32",
            "minimum": 1,
            "maximum": 1000,
            "example": 12
          },
          "places": {
            "type": "integer",
            "format": "int32",
            "minimum": 1,
            "maximum": 100,
            "example": 5
          },
          "isVip": {
            "type": "boolean"
          },
          "minOrder": {
            "type": "integer"
          }
        },
        "required": [
          "id",
          "number",
          "places",
          "isVip"
        ],
        "x-examples": {
          "Example 1": {
            "id": 5,
            "number": 12,
            "places": 5,
            "isVip": true,
            "minOrder": 120
          }
        }
      },
      "Reservation": {
        "type": "object",
        "properties": {
          "tableNumber": {
            "type": "integer",
            "format": "int32",
            "minimum": 1,
            "example": 12
          },
          "clientName": {
            "type": "string",
            "example": "Jim Smith"
          },
          "phoneNumber": {
            "type": "string",
            "example": "949 213-3433"
          },
          "date": {
            "type": "string",
            "format": "date",
            "example": "2024-09-20"
          },
          "slotTimeStart": {
            "type": "string",
            "pattern": "^[0-2]{0,1}\\d:[0-5]\\d$",
            "example": "3:00"
          },
          "slotTimeEnd": {
            "type": "string",
            "pattern": "^[0-2]{0,1}\\d:[0-5]\\d$",
            "example": "15:00"
          }
        },
        "required": [
          "tableNumber",
          "clientName",
          "phoneNumber",
          "date",
          "slotTimeStart",
          "slotTimeEnd"
        ],
        "x-examples": {
          "Example 1": {
            "tableNumber": 12,
            "clientName": "Jim Smith",
            "phoneNumber": "949 231-3421",
            "date": "2024-09-20",
            "slotTimeStart": "13:00",
            "slotTimeEnd": "15:00"
          }
        }
      }
    }
  }
}